name: 🤖 Auto move new issues into triage
on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.0
        with:
          project-url: ${{ github.server_url }}/orgs/${{ github.repository_owner }}/projects/1
          github-token: ${{ secrets.ROUTELINKBOT_TOKEN }}
